### ISSUE TITLE
Timer not accurate

### ISSUE THREAD

**Issue by amitkumarcoding** [shubhambathe1/react-native-countdown-timer-hooks#1]
countdown timer is not accurate, it's around 2-5 secs difference as compare to mobile timer

**Comment by shubhambathe1** [comment]
@amitmehtacode Thanks for pointing out the issue that your facing. But can your describe the problem in bit more details. As far as I have tested the library, I did not find any issue with the timer accuracy. It would be really helpful if you add some screenshots/videos along with your problem statement for better understanding & clarifications. Also please add your environment variables details using (npx react-native info).
