### ISSUE TITLE
Timer doesn't display properly for certain times

### ISSUE THREAD

**Issue by JustusWest** [shubhambathe1/react-native-countdown-timer-hooks#2]

**Comment by JustusWest** [comment]
When given a timestamp such that days > 0 but hours == 0, the timer will display only minutes and seconds:
ie, should display 2:00:10:30 but only displays 10:30.
Can be fixed by changing the if statements starting at line 65 of index.js to else ifs:
`    
let displayTime = "";

    if (days !== 0) {
      displayTime = `${days}:${hr}:${min}:${sec}`;
    }
    else if (days === 0 && hours !== 0) {
      displayTime = `${hr}:${min}:${sec}`;
    }

    else if (hours === 0 && minutes !== 0) {
      displayTime = `${min}:${sec}`;
    }

    else if (minutes === 0 && seconds !== 0) {
      displayTime = `${min}:${sec}`;
    }
`

**Comment by shubhambathe1** [comment]
@JustusWest Thanks a lot for pointing out this edge case. Your suggested code did not work directly, but after some modification, trials and errors I got it fixed. Here are the changes that were made:-

```
if (days !== 0) {
  displayTime = `${days}:${hr}:${min}:${sec}`;
}

if (days === 0 && hours !== 0) {
  displayTime = `${hr}:${min}:${sec}`;
}

if (days === 0 && hours === 0 && minutes !== 0) {
   displayTime = `${min}:${sec}`;
}

if (days === 0 && hours === 0 && minutes === 0 && seconds !== 0) {
  displayTime = `${min}:${sec}`;
}
```

I will push the latest code in npm.js repo soon. Please do test it again let me know if that works.

**Comment by JustusWest** [comment]
@shubhambathe1  Thank you! Please do push the code and I will test it in my app.

**Comment by shubhambathe1** [comment]
@JustusWest I have already updated the lib version (v 1.0.4). You can find it here:- [package link](https://www.npmjs.com/package/react-native-countdown-timer-hooks)
