### ISSUE TITLE
Get Time left

### ISSUE THREAD

**Issue by marlene89** [shubhambathe1/react-native-countdown-timer-hooks#3]
Is there a way to get time left on timer? Like an onChange or onProgress tracker? I'd like to change timer styling when there is about 30 seconds left on the timer but I couldn't find a way to track the timer's progress except when the timer completely runs out.

**Comment by shubhambathe1** [comment]
@marlene89 As of now the timer component does support tracking progress of passed time. But it's definitely good to have such a feature for this component. I will try to develop and push this functionality as soon as possible. In the mean time if you can develop this functionality and raise a PR for the same that would be really appreciated. By the way thanks for reaching out. 🤝

**Comment by shubhambathe1** [comment]
@marlene89 Please refer the new version (v 1.0.5) of the library. Progress tracker callback has been added.

**Comment by shubhambathe1** [comment]
Closed due to inactivity.
